CREATE DATABASE exercise1;
CREATE TABLE EMP_1(EMP_NUM CHAR(3) NOT NULL, EMP_Lname VARCHAR(15) NULL, EMP_FNAME VARCHAR(15) NULL, EMP_INITIAL VARCHAR(1) NULL, EMP_HIREDATE DATE NULL, JOB_CODE CHAR(3) NULL);
SELECT *FROM EMP_1;
INSERT INTO emp_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES('1','San Pascual', 'Mara', 'T', '2020-09-23', '501');
INSERT INTO emp_1(EMP_NUM, EMP_Lname, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES('2','Isidro', 'Kassandra', 'P', '2020-09-01', '502');
SELECT *FROM EMP_1
WHERE JOB_CODE = '502';
